apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chat-app-db
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: chat-app-db
    spec:
      containers:
        - image: postgres
          imagePullPolicy: Always
          name: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-config